---

- name: create phoenix queryserver systemd service file
  template: src=systemd/phoenix-queryserver.service.j2 dest=/etc/systemd/system/phoenix-queryserver.service
  notify:
    - restart phoenix queryserver
  tags:
    - phoenix
    - phoenix_queryserver

- name: start phoenix queryserver
  service: name=phoenix-queryserver state=started enabled=yes
  tags:
    - phoenix
    - phoenix_queryserver
