# -*- mode: ruby -*-
# vi: set ft=ruby :

# ------------------------- CONFIG PARAMS ----------------------------
provider = "virtualbox"      # VM provider
type = "ubuntu/trusty64"
RAM = 16384                  # When testing Tachyon
CPUs = 2                     # CPU cores
Name = "ansible"             # name of the master node (used in scripts/spark-env-sh)
# -------------------------- END CONFIG PARAMS -----------------------


Vagrant.configure(2) do |config|
# config Admin node
  config.vm.boot_timeout = 600 
  config.vm.define Name do |admin|
    admin.vm.box = type
    admin.vm.hostname = Name
    admin.vm.provider provider do |vb|
      vb.memory = RAM
      vb.cpus = CPUs 
      vb.name = Name
    end
    # Forward local host port 8080 to zeppelin port 8080
    admin.vm.network "forwarded_port", guest: 8080, host: 8888
    admin.vm.provision :shell, :path => "bootstrap.sh", privileged: false
  end
end
