---
- name: Create the Apps directory
  file: path=/home/{{ cluster_user }}/apps state=directory owner={{ cluster_user }} group={{ cluster_user }} mode=0777 recurse=yes

- name: Copy Spark-kernel to Apps directory
  copy: src=spark-kernel-0.1.5-SNAPSHOT.tar.gz dest=/home/{{ cluster_user }}/apps mode=0777

- name: Create scripts directory
  file: path=/home/{{ cluster_user }}/scripts state=directory owner={{ cluster_user }} group={{ cluster_user }} mode=0777 recurse=yes

- name: Copy deployment scripts
  template: src={{ item.src }} dest={{ item.dest }} owner={{ cluster_user }} group={{ cluster_user }} mode=0777
  with_items:
    - {src: "00-init.sh.j2", dest: "/home/{{ cluster_user }}/scripts/00-init.sh"}
    - {src: "10-java-python-scala.sh.j2", dest: "/home/{{ cluster_user }}/scripts/10-java-python-scala.sh"}
    - {src: "20-spark.sh.j2", dest: "/home/{{ cluster_user }}/scripts/20-spark.sh"}
    - {src: "30-R.sh.j2", dest: "/home/{{ cluster_user }}/scripts/30-R.sh"}
    - {src: "40-jupyter.sh.j2", dest: "/home/{{ cluster_user }}/scripts/40-jupyter.sh"}
    - {src: "41-test_helper.sh.j2", dest: "/home/{{ cluster_user }}/scripts/41-test_helper.sh"}
    - {src: "42-rise.sh.j2", dest: "/home/{{ cluster_user }}/scripts/42-rise.sh"}
    - {src: "43-spark-kernel.sh.j2", dest: "/home/{{ cluster_user }}/scripts/43-spark-kernel.sh"}
    - {src: "44-irkernel.sh.j2", dest: "/home/{{ cluster_user }}/scripts/44-irkernel.sh"}
    - {src: "45-jupyter-extensions.sh.j2", dest: "/home/{{ cluster_user }}/scripts/45-jupyter-extensions.sh"}
    - {src: "50-rstudio-server.sh.j2", dest: "/home/{{ cluster_user }}/scripts/50-rstudio-server.sh"}
    - {src: "51-shiny-server.sh.j2", dest: "/home/{{ cluster_user }}/scripts/51-shiny-server.sh"}
    - {src: "60-cassandra.sh.j2", dest: "/home/{{ cluster_user }}/scripts/60-cassandra.sh"}
    - {src: "70-zeppelin.sh.j2", dest: "/home/{{ cluster_user }}/scripts/70-zeppelin.sh"}
    - {src: "99-clean.sh.j2", dest: "/home/{{ cluster_user }}/scripts/99-clean.sh"}
    - {src: "box-provision.sh.j2", dest: "/home/{{ cluster_user }}/scripts/box-provision.sh"}
    - {src: "dsbox.sh.j2", dest: "/home/{{ cluster_user }}/scripts/dsbox.sh"}
    - {src: "jupyter_notebook_config.py.j2", dest: "/home/{{ cluster_user }}/scripts/jupyter_notebook_config.py"}
    - {src: "kernel.json.j2", dest: "/home/{{ cluster_user }}/scripts/kernel.json.j2"}
    - {src: "start-pyspark-notebook.sh.j2", dest: "/home/{{ cluster_user }}/scripts/start-pyspark-notebook.sh"}
 
 # ssh and manually test