---
- name: Create the Flink slaves file on Flink master
  template: src=slaves.j2 dest={{ spark_home }}/conf/slaves owner={{ cluster_user }} group={{ cluster_user }}





#- name: Copy Flink configuration settings
#  template: src=spark-env.sh.j2 dest={{ spark_home }}/conf/spark-env.sh owner={{ cluster_user }} group={{ cluster_user }} mode=0777
