---
- name: Stop Cassandra
  service: name=cassandra enabled=yes state=stopped

- name: Clean default configuration
  shell: sudo rm -rf /var/lib/cassandra/data/system*

- name: Copy the configuraiton template
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/cassandra.yaml

- name: Start the Cassandra Cluster
  service: name=cassandra enabled=yes state=started

# On the first node of the cluster, run:
#sudo nodetool -status