---

- name: configure hdfs
  template:
    src: 'hdfs-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/hdfs-site.xml'
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
  tags:
    - hadoop
    - hdfs
  notify:
    - restart hdfs namenode
    - restart hdfs secondarynamenode
    - restart hdfs datanode

- include: namenode.yml
  when: '"hdfs_namenode" in group_names'

- include: secondarynamenode.yml
  when: '"hdfs_secondarynamenode" in group_names'

- include: datanode.yml
  when: '"hdfs_datanode" in group_names'

