---
- hosts: all
  tasks:
    - name: Create Admins group
      group: name=admin state=present
      sudo: yes

    - name: Create Admin user on all nodes
      user: name={{ cluster_user }}
            comment="Cluster Administrator"
            group={{ cluster_user }}
            createhome=yes
            home=/home/{{ cluster_user }}
            shell=/bin/bash
            password={{ cluster_password |password_hash('sha512') }}
            generate_ssh_key=yes
            ssh_key_bits=2048
            state=present
      sudo: yes

    - name: Add Admin user to sudoers
      lineinfile: "dest=/etc/sudoers insertafter=EOF line='{{ cluster_user }} ALL=(ALL) NOPASSWD: ALL' regexp='{{ cluster_user }} ALL=(ALL) NOPASSWD: ALL' state=present"
      sudo: yes

    - name: Ensure Admin user ssh directory exists
      file: dest=/home/{{ cluster_user }}/.ssh owner={{ cluster_user }} group={{ cluster_user }} state=directory mode=0700
      sudo: yes
      
    - name: Disable strict host checking for the Admin user
      lineinfile: create=yes
                  dest=/home/{{ cluster_user }}/.ssh/config
                  regexp=StrictHostKeyChecking
                  line="StrictHostKeyChecking no"
                  owner={{ cluster_user }}
                  group={{ cluster_user }}
                  mode=0644
      become: yes
      become_user: "{{ cluster_user }}"
    
- hosts: master
  tasks:
    - name: Setup passwordless ssh
      shell: /bin/cat /home/{{ cluster_user }}/.ssh/id_rsa.pub >> /home/{{ cluster_user }}/.ssh/authorized_keys
      become: yes
      become_user: "{{ cluster_user }}"
    
    - name: Create local directory for ssh keys
      #local_action: command mkdir sshkeys
      local_action: file path=sshkeys state=directory
    
    - name: Fecth ssh keys from the master
      fetch: src=/home/{{ cluster_user }}/.ssh/{{ item }} dest=sshkeys/{{ item }} flat=yes
      with_items:
        - id_rsa
        - id_rsa.pub
        - authorized_keys
      become: yes
      become_user: "{{ cluster_user }}"

- hosts: slaves
  tasks:
    - name: Distribute ssh keys to slaves
      copy: src=sshkeys/{{ item }} dest=/home/{{ cluster_user }}/.ssh/{{ item }}
      with_items:
        - id_rsa
        - id_rsa.pub
        - authorized_keys
      become: yes
      become_user: "{{ cluster_user }}"
    
    - name: Ensure correct permissions on the ssh keys
      file: path=/home/{{ cluster_user }}/.ssh/{{ item }} mode=0600 owner={{ cluster_user }} group={{ cluster_user }}
      with_items:
        - id_rsa
        - id_rsa.pub
        - authorized_keys
      become: yes
      become_user: "{{ cluster_user }}"

- name: Install base confiuration on all servers
  hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - common

- name: Install hadoop on all servers
  hosts: all
  remote_user: vagrant
  sudo: yes
  
  roles:
    - hadoop

- name: Install spark on all servers
  hosts: all
  remote_user: vagrant
  sudo: yes
  
  roles:
    - spark

- name: Configure manual master configuration to test
  hosts: master
  remote_user: vagrant
  sudo: yes
  
  roles:
    - dsbox

#- name: Install and configure the master
#  hosts: master
#  remote_user: vagrant
#  sudo: yes
#
#  roles:
#    - master