# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load the initialization file `init.yml`
@cmd = YAML.load_file('init.yml')
puts @cmd.inspect

# ------------------------- GLOBAL CONFIG PARAMS ----------------------------
Total = @cmd['Total']
Username = @cmd['Username']
Password = @cmd['Password']
Pool = @cmd['Pool']
Cluster = @cmd['Cluster']
Template = @cmd['Template']
Host = @cmd['Host']
Spark_Version = @cmd['Spark_Version']
Master_User = @cmd['Master_User']
Master_Password = @cmd['Master_Pass']
Maven_Version = @cmd['Maven_Version']
DSE_Version = @cmd['DSE_Version']
Scala_Version = @cmd['Scala_Version']
TFlow_Version = @cmd['TFlow_Version']
RStudio_Server = @cmd['RStudio_Server']
Shiny_Version = @cmd['Shiny_Version']
# -------------------------- END GLOBAL CONFIG PARAMS -----------------------

groups = {
  "admin" => [],
  "dse" => [],
  "flink" => [],
  "all_groups:children" => ["admin", "dse", "flink"]
}

Vagrant.configure("2") do |config|
  config.vm.box = 'aws'

# -------------------------------- TO-DO -------------------------------------
# Add AWS dummy boc from https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
# to "example_box" directory. May want to use `vagrant box add dummy .\path\to\box`
# instead of simply copying the RAW download. May also need to run `vagrant init`
# -----------------------------------------------------------------------------

  config.vm.box_url = './example_box/dummy.box'
  config.vm.boot_timeout = 600
  (1..Total).each do |i|
    if i == 1
      name = "admin"
      groups["admin"] << name
    elsif i >= 7
      name = "flink-#{i - 7}"
      groups["flink"] << name
    else
      name = "dse-#{i - 1}"
      groups["dse"] << name
    end
    config.vm.define "#{name}" do | config |
      config.vm.hostname = name
      if i == Total
        config.vm.provision :ansible do |ansible|
          ansible.playbook = "site.yml"
          ansible.groups = groups
          ansible.extra_vars = {
            "dse_version" => DSE_Version,
            "rstudio_server" => RStudio_Server,
            "shiny_version" => Shiny_Version,
            "spark_version" => Spark_Version,
            "maven_version" => Maven_Version,
            "tflow_version" => TFlow_Version,
            "scala_version" => Scala_Version,            
            "cluster_user" => Master_User,
            "cluster_password" => Master_Password
          }
          ansible.limit = "all"
          ansible.verbose = "v"
          ansible.raw_ssh_args = ['-o ControlPersist=30m']
        end
      end
      
      # AWS Config
      config.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']
        aws.ami = "ami-a7fdfee2"
        aws.region = ENV['AWS_REGION']
        aws.instance_type = "t2.micro"
        
        override.vm.box = "dummy"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end
    end
  end
end

# Vagrantfile
Vagrant.configure(2) do |config|
 config.vm.provider :aws do |aws, override|
   aws.access_key_id = ENV['AWS_KEY']
   aws.secret_access_key = ENV['AWS_SECRET']
   aws.keypair_name = ENV['AWS_KEYNAME']
   aws.ami = "ami-a7fdfee2"
   aws.region = "us-west-1"
   aws.instance_type = "t2.micro"

   override.vm.box = "dummy"
   override.ssh.username = "ubuntu"
   override.ssh.private_key_path = ENV['AWS_KEYPATH']
 end