---
- name: Create the Apps directory
  file: path=/home/{{ cluster_user }}/apps state=directory owner={{ cluster_user }} group={{ cluster_user }} mode=0777 recurse=yes

- name: Copy Spark-kernel to Apps directory
  copy: src=spark-kernel-0.1.5-SNAPSHOT.tar.gz dest=/home/{{ cluster_user }}/apps mode=0777

- name: Copy deployment script
  template: src=repl.sh.j2 dest=/home/{{ cluster_user }} mode=0777

# ssh and manually test
