# -*- mode: ruby -*-
# vi: set ft=ruby :

# ------------------------- GLOBAL CONFIG PARAMS ------------------------------------
Total = 6                                    # Total Number of hosts
Username = "administrator@vsphere.local"     # vSphere Username
Password = "Fuck_Y0u!"                       # vSphere Password
Cluster = "VRTX"                             # vSphere Cluster
Template = "centos7-tmp"                     # Template to clone from
Host = "vcenter.synapse.local"               # vCenter Host
Master_User = "cluster"                      # Master ssh user for the cluster
Master_Password = "cluster"                  # Master ssh pasword for the cludster
DCOS_Installer = "https://downloads.dcos.io/dcos/EarlyAccess" #DC/OS URL
# -------------------------- END GLOBAL CONFIG PARAMS ------------------------------

# Build Ansible Groups to dynamically add Virtual Machines
groups = {
  "other" => [],
  "masters" => [],
  "workers" => [],
  "all_groups:children" => ["other", "masters", "workers"]
}

Vagrant.configure("2") do |config|
  config.vm.box = 'vsphere'
  config.vm.box_url = './example_box/dummy.box'
  config.vm.boot_timeout = 600
  (1..Total).each do |i|
    if i == 1
      name = "bootstrap"
      groups["other"] << name
    elseif i <= 4 and i! = 1
      name = "master-#{i - 1}"
      groups["masters"] << name
    else
      name = "worker-#{i - 4}"
      groups["workers"] << name
    end
    config.vm.define "#{name}" do | config |
      config.vm.hostname = name
      if i == Total
        config.vm.provision :ansible do |ansible|
          ansible.playbook = "site.yml"
          ansible.groups = groups
          ansible.extra_vars = {
            "dcos_url" => DCOS_Installer,
            "cluster_user" => Master_User,
            "cluster_password" => Master_Password
          }
          ansible.limit = "all"
          ansible.verbose = "v"
          ansible.raw_ssh_args = ['-o ControlPersist=30m']
        end
      end
      config.vm.provider :vsphere do |vsphere|
        vsphere.name = name
        vsphere.template_name = Template
        vsphere.linked_clone = false
        vsphere.host = Host
        vsphere.insecure = true
        vsphere.compute_resource_name = Cluster
        vsphere.user = Username
        vsphere.password = Password
      end  
    end
  end
end