---

- name: create hdfs namenode data directory
  file: path={{ hdfs_namenode_name_dir }} state=directory owner={{ hadoop_user }} group={{ hadoop_group }}
  register: create_hdfs_namenode_data_dir

- name: format hdfs namenode data directory
  command: '{{ hadoop_home }}/bin/hadoop namenode -format'
  when: create_hdfs_namenode_data_dir|changed
  sudo: yes
  sudo_user: '{{ hadoop_user }}'

- name: create hdfs namenode systemd service file
  template: src=systemd/hdfs-namenode.service.j2 dest=/etc/systemd/system/hdfs-namenode.service

- name: start hdfs namenode
  service: name=hdfs-namenode state=started enabled=yes
