---

- name: create mapred historyserver systemd service file
  template: src=systemd/mapred-historyserver.service.j2 dest=/etc/systemd/system/mapred-historyserver.service
  tags:
    - mapred
    - mapred_historyserver
    - hadoop

- name: start mapred historyserver
  service: name=mapred-historyserver state=started enabled=yes
  tags:
    - mapred
    - mapred_historyserver
    - hadoop
