---














#-----------------------------------------------------------------------------------------------------------------------------------------
#echo "# Upgrade to Java 8" #http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
#sudo add-apt-repository ppa:webupd8team/java
#sudo apt-get update
#echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
#sudo apt-get -y install oracle-java8-installer
#sudo apt-get -y install oracle-java8-set-default
#echo "# Install DataStax Distribution of Apache Cassandra"
#echo "deb http://debian.datastax.com/datastax-ddc $CASSANDRA_VER main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
#curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -
#sudo apt-get update
## install Cassandra utils->sstablelevelreset, sstablemetadata, sstableofflinerelevel, sstablerepairedset, sstablesplit, token-generator.
#sudo apt-get -y install datastax-ddc

## Because the Cassandra service starts automatically, stop the server and clear the data on each node
#sleep 60 # wait for cassandra to fully start
#sudo service cassandra stop
#sudo rm -rf /var/lib/cassandra/data/system/*

# Initialize cassandra muli-node cluster (single data center)
# configure Cassandra (see http://docs.datastax.com/en/cassandra/3.x/cassandra/initialize/initSingleDS.html); 
# https://www.digitalocean.com/community/tutorials/how-to-use-the-apache-cassandra-one-click-application-image
# and https://github.com/danielrmeyer/cassandra-analytics/blob/c337dfe726e7846f51cdb303741d78284da8a8f2/provisioning/setup_cassandra.sh
#NODE_IP = `hostname -I | cut -d' ' -f2`

#NODE_IP=$(ip -4 address show eth1 | grep 'inet' | sed 's/.*inet \([0-9\.]\+\).*/\1/')
#sudo sed -i "s/cluster_name: 'Test Cluster'/cluster_name: 'MyCassandraCluster'/g" /etc/cassandra/cassandra.yaml
##Seed nodes are used to bootstrap new nodes into the cluster. Set the master as the seed node.
##sudo sed -i "s/seeds: \"127.0.0.1\"/seeds: \"${IP}0\"/g" /etc/cassandra/cassandra.yaml
#sudo sed -i "s/seeds: \"127.0.0.1\"/seeds: \"10.20.30.100\"/g" /etc/cassandra/cassandra.yaml
#sudo sed -i "s/listen_address: localhost/listen_address:/g" /etc/cassandra/cassandra.yaml
#sudo sed -i "s/rpc_address: localhost/rpc_address: 0.0.0.0/g" /etc/cassandra/cassandra.yaml
#sudo sed -i "s/# broadcast_rpc_address: 1.2.3.4/broadcast_rpc_address: $NODE_IP/g" /etc/cassandra/cassandra.yaml
## Start Cassandra Cluster
#sudo service cassandra start
