---

- name: configure yarn
  template:
    src: 'yarn-site.xml.j2'
    dest: '{{ hadoop_home }}/etc/hadoop/yarn-site.xml'
    owner: '{{ hadoop_user }}'
    group: '{{ hadoop_group }}'
  tags:
    - hadoop
    - yarn
  notify:
    - restart yarn resourcemanager
    - restart yarn nodemanager

- include: resourcemanager.yml
  when: '"yarn_resourcemanager" in group_names'

- include: nodemanager.yml
  when: '"yarn_nodemanager" in group_names'

